# yaml-language-server: $schema=./apis-config.schema.json
print_sql: true

sqlalchemy_database_uri: "postgresql+psycopg://postgres:passwd@localhost:15432/dataetat"

keycloak_openid:
  url: https://auth.nocode.csm.ovh
  realm: "Regions"
  client_id: "back-api"
  secret_key: "hNFljZDqcKehP0qJiB82VP6wxKRuu1RC"
  test_user: <TEST_USER>
  test_password: <TEST_PASSWORD>
