print_sql: true

sqlalchemy_database_uri: "postgresql+psycopg://postgres:passwd@localhost:5432/<DBNAME>"
sqlalchemy_database_uri_audit: "postgresql+psycopg://postgres:passwd@localhost:5432/<DBNAME_AUDIT>"

dossier_des_exports: "/tmp/DataEtat/exports"
dossier_des_telechargements: "/tmp/DataEtat/cached_remote_files"

grist:
  database_url: "postgresql+psycopg://postgres:passwd@localhost:5432/grist"
  serveur_url: "https://grist.instance.fr"
  token_scim: "<TOKEN_SCIM>"

cached_remote_files_url:
  donnees_qpv_entreprises: "https://www.data.gouv.fr/fr/datasets/r/ba6a4e4c-aac6-4764-bbd2-f80ae345afc5"
