[tool.importlinter]
root_packages = [
  "batches",
  "services",
  "models",
] 

[[tool.importlinter.contracts]]
name = "L'architecture en couche est respect√©e"
type = "layers"
layers = [
  "batches",
  "services",
  "models",
]
